services:
  - type: cron
    name: check-nulls-cron
    env: python
    plan: free
    schedule: "*/5 * * * *"  # Executa a cada 5 minutos
    buildCommand: pip install -r requirements.txt
    startCommand: python check_nulls.py
    envVars:
      - key: DB_URL
        value: postgresql://admin:pR6aFnyZm6nc1wlCheGVXvjJ5VZrLZQ6@dpg-d0d26gjuibrs73dra1tg-a.oregon-postgres.render.com/contazoom?sslmode=require
